### ISSUE TITLE
Page Layout, Print Size Glitch?

### ISSUE THREAD

**Issue by jscelsa** [mcneel/rhinoissues#43]
I am having a problem with page layouts in v5 beta.

The layouts create fine as they have for several months now but when i create a new viewport and edit the viewport to say tabload from letter it keeps reverting to letter. 

In other words I can not seem to affect change to the page size. I am fairly certain this is a glitch in a subsequent release and not user error as I have done this in the past.

**Comment by jscelsa** [comment]
Just to add to my posting. I realized that the custom width and height input worked to affect the page size. its just the select pre-established sizes that do not force a change.

**Comment by sbaer** [comment]
This should be fixed in next week's beta
