### ISSUE TITLE
DimArea not working with Blocks

### ISSUE THREAD

**Issue by davouch** [mcneel/rhinoissues#58]
When in block editing mode, adding an area dimension with DimArea command works properly, but when ending the Block Editing mode (via OK button on the Block Edit dialog), all the Area Dimensions get n/a showing "####".
Currently I'm not aware of any way to reassociate 'em back with their originally messured objects.

Update: It's messed in the very same way, when trying to create DimArea on any geometry contained in some block.

**Comment by sbaer** [comment]
We are moving these issues to our 'real' issue tracker. This issue is filed at
http://mcneel.myjetbrains.com/youtrack/issue/RH-20373
