### ISSUE TITLE
Join surfaces, from 2D to 3D

### ISSUE THREAD

**Issue by pihuggins** [mcneel/rhinoissues#59]
I am making 2D paper patterns and then joining them by picking edges to match and want Rhino to distort the materials from 2D to 3D as needed to match the edges. E.g., make a cylinder from a rectangle with an edge as long as the circumference of a circle. That's easy, but what about pants? This is sort of reverse engineering. Maybe it is already a feature. I admit I am a user who has not poked around much, but I do love the software.

**Comment by sbaer** [comment]
Sorry, we should be closing this issue site down. I would recommend discussing this at
http://discourse.mcneel.com/
