### ISSUE TITLE
Make2D

### ISSUE THREAD

**Issue by Architectofc** [mcneel/rhinoissues#61]
I usually use the command make2D For me it is one of the most useful commands in Rhino.

I beg you to improve as it gives several lines, some are cut, and often have to touch. I think it is a very useful command but needs improvement.

It would be interesting a couple of points:
- Signs: Allow customize a field for the command to draw each of the views, write below it the text that the user enters. Example: Top view, Elevation view, ...
- Multiple Parts: On many occasions I need to get the drawings of hundreds of pieces to make drawings of each. I have to go selecting piece by piece. Interesting would be to select a hundred pieces and draw the command four views of each. Customizing the user to indicate the distance between the centers of each complex views. 

Example: I have 100 pieces and 100 A4 format in Top view. The distance between the centers of the A4 is 300mm I want one drawing every 300mm to coincide with the formats. Rhino draw 4 views of 100 single pieces in the centers of the A4.
- Views: It would be interesting to select which views the user wants, because in my case, I am very interested to get plan, elevation, view right and left view.
  Sometimes I'm interested in the perspective view. I'd like to put an option to mark a fixed perspective. For example an orthographic view. So that all the pieces I have to draw have the same point of view.

I hope this can help to improve Rhinoceros

**Comment by dalefugier** [comment]
This is an issue best discussed on our Discourse discussion forum. Would you might moving the conversation there?

http://discourse.mcneel.com/

Thanks!
