### ISSUE TITLE
Minimum Bounding box

### ISSUE THREAD

**Issue by Architectofc** [mcneel/rhinoissues#62]
Getting that calculates the minimum bounding box to fill the entire piece. Whatever their orientation.

Now creates a bounding box parallel to the plane C
For me it is very interesting to know what the minimum bounding box regardless of its orientation in space. I want to calculate the minimum dimensions of material to get through CNC the pieces.

**Comment by dalefugier** [comment]
This is an issue best discussed on our Discourse discussion forum. Would you might moving the conversation there?

http://discourse.mcneel.com/

Thanks!
